- name: Centos update / Reboot
  hosts: all
  tasks:
    - name: Send a success email
      mail:
        host: mailhost.centorial.local
        port: 25 
        from: abouchelliga@lesechosleparisien.fr
        to: abouchelliga@lesechosleparisien.fr
        subject: Installation Update start
        body: 'The installation is Starting on ** {{ ansible_hostname }} **Server.'
    - name: Perform yum update of all packages
      yum:
        name: '*'
        state: latest
      async: 3600
      poll: 0
      register: yum_sleeper
    - name: Check on async task of yum update
      async_status:
        jid: "{{ yum_sleeper.ansible_job_id }}"
      register: job_result
      until: job_result.finished
      retries: 5000
    - debug:
        msg: "Yum update of server {{ ansible_hostname }} has been completed."
    - name: Check for reboot
      shell: if [ $(rpm -q kernel|tail -n 1) != kernel-$(uname -r) ]; then echo 'reboot'; else echo 'no'; fi
      ignore_errors: true
      register: reboot_hint

    - name: reboot the server if required
        shell: sleep 3; reboot
        ignore_errors: true
        changed_when: false
        async: 1
        poll: 0
      - name: wait for server to come back after reboot
        wait_for_connection:
          timeout: 600
          delay: 20
        register: reboot_result
      - name: reboot time
        debug:
          msg: "The system rebooted in {{ reboot_result.elapsed }} seconds."
    - name: Send a success email
      mail:
        host: mailhost.centorial.local
        port: 25 
        from: abouchelliga@lesechosleparisien.fr
        to: abouchelliga@lesechosleparisien.fr
        subject: Installation Update finished
        body: 'The installation is Finished.
               Server {{ ansible_hostname }} was rebooted --- {{ job_result }}---'
