- name: Install IIS
  hosts: all
  tasks:
  - name: install-iis
    win_feature:
      name: "Web-Server"
      state: present
      restart: yes
      include_sub_features: yes
      include_management_tools: no
