- name: List_Packages
  hosts: all
  tasks:
    - name: yum_command 
      yum:
        list=installed
      register: yum_packages

    - debug: var=item
      with_items: 
         - "{{yum_packages|json_query(jsonquery)}}"
         - "{{yum_packages|json_query(jsonquery2)}}"
      vars:
        jsonquery: "results[?name=='GeoIP']"
        jsonquery2: "results[?name=='GeoIP']"
