- name: Install updates
  hosts: all
  tasks:
  
   - name: Search-only, return list of found updates 
     win_updates:
       category_names: SecurityUpdates
       state: searched
       register: result
   
       
   #- name: install all critical and security updates
    # win_updates:
     #  category_names:
      # - CriticalUpdates
       #- SecurityUpdates
       #state: installed
     #register: update_result

   - name: Install only particular updates based on the KB numbers (KB4048953)
     win_updates:
       category_name:
       - SecurityUpdates
       whitelist:
       - KB4495586
       
   - name: reboot if required
     win_reboot:
       reboot_timeout_sec: 3600
     when: update_result.reboot_required
