- name: Install updates
  hosts: all
  tasks:
   - name: install all critical and security updates
     win_updates:
       category_names:
       - CriticalUpdates
       - SecurityUpdates
       state: installed
     register: update_result

   - name: reboot if required
     win_reboot:
       reboot_timeout_sec: 3600
     when: update_result.reboot_required
