- name: Install updates
  hosts: all
  gather_facts: false
  tasks:
    #Send mail notification
    - name: Send a success email
      mail:
        host: mailhost.centorial.local
        port: 25 
        from: abouchelliga@lesechosleparisien.fr
        to: abouchelliga@lesechosleparisien.fr
        subject: Installation Update start
        body: 'The installation is Starting on ** {{ ansible_hostname }} **Server.'
        
   # Check if there are missing updates
    - name: Check for missing updates.
      win_updates: state=installed
      register: update_count
        
 
    #Install missing updates only if at least one is missing
    - name: Install missing updates.
      win_updates:
       category_names: ['SecurityUpdates','CriticalUpdates','UpdateRollups', 'Updates', 'DefinitionUpdates']
      register: result

    # output results
     
    - name: Reboot, if needed.
      win_reboot:
      when: result.reboot_required
    #Send mail notification  
    - name: Send a success email
      mail:
        host: mailhost.centorial.local
        port: 25 
        from: abouchelliga@lesechosleparisien.fr
        to: abouchelliga@lesechosleparisien.fr
        subject: Installation Update Finsih
        body: 'The installation is Finished on ** {{ ansible_hostname }} **Server.'
